-- Basic integration test for the Lua ggml module built by CMake.
-- Run from repo root: lua tests/test.lua

package.cpath = "./build/?.so;../build/?.so;" .. package.cpath

local ok, ggml = pcall(require, "ggml")
if not ok then
    io.stderr:write("Failed to require 'ggml': " .. tostring(ggml) .. "\n")
    io.stderr:write("Tip: build first with cmake, then run this script from repo root.\n")
    os.exit(1)
end

assert(type(ggml) == "table", "ggml module should return a table")
assert(type(ggml.init) == "function", "ggml.init should be a function")
assert(type(ggml.free) == "function", "ggml.free should be available from autogenerated bindings")
assert(type(ggml.permute) == "function", "ggml.permute should be available from autogenerated bindings")
assert(type(ggml.new_tensor_2d) == "function", "ggml.new_tensor_2d should be available")
assert(type(ggml.mul_mat) == "function", "ggml.mul_mat should be available")
assert(type(ggml.new_graph) == "function", "ggml.new_graph should be available")
assert(type(ggml.build_forward_expand) == "function", "ggml.build_forward_expand should be available")
assert(type(ggml.graph_compute_with_ctx) == "function", "ggml.graph_compute_with_ctx should be available")
assert(type(ggml.set_f32_1d) == "function", "ggml.set_f32_1d should be available")
assert(type(ggml.get_f32_1d) == "function", "ggml.get_f32_1d should be available")
assert(type(ggml.TYPE_F32) == "number", "ggml.TYPE_F32 constant should be available")
assert(type(ggml.STATUS_SUCCESS) == "number", "ggml.STATUS_SUCCESS constant should be available")

local mem_size = 16 * 1024 * 1024 -- 16 MiB
local ctx = ggml.init(mem_size)
assert(type(ctx) == "userdata", "ggml.init should return userdata")

-- Matrix setup copied from the C++ ggml matmul example.
-- A is 4x2, B is 3x2; ggml_mul_mat(A, B) computes A * B^T and stores
-- result as ne0=4, ne1=3 (printed transposed in the example).
local rows_A, cols_A = 4, 2
local rows_B, cols_B = 3, 2

local matrix_A = {
    2, 8,
    5, 1,
    4, 2,
    8, 6,
}

local matrix_B = {
    10, 5,
    9, 9,
    5, 4,
}

local a = ggml.new_tensor_2d(ctx, ggml.TYPE_F32, cols_A, rows_A)
local b = ggml.new_tensor_2d(ctx, ggml.TYPE_F32, cols_B, rows_B)

for i, v in ipairs(matrix_A) do
    ggml.set_f32_1d(a, i - 1, v)
end

for i, v in ipairs(matrix_B) do
    ggml.set_f32_1d(b, i - 1, v)
end

local result = ggml.mul_mat(ctx, a, b)
local gf = ggml.new_graph(ctx)
ggml.build_forward_expand(gf, result)

local status = ggml.graph_compute_with_ctx(ctx, gf, 1)
assert(status == ggml.STATUS_SUCCESS, "graph_compute_with_ctx failed with status " .. tostring(status))

local expected = {
    60.0, 55.0, 50.0, 110.0,
    90.0, 54.0, 54.0, 126.0,
    42.0, 29.0, 28.0, 64.0,
}

for i, want in ipairs(expected) do
    local got = ggml.get_f32_1d(result, i - 1)
    local delta = math.abs(got - want)
    assert(delta < 1e-5, string.format("matmul mismatch at index %d: got %.6f want %.6f", i - 1, got, want))
end

local ok_missing_arg, err_missing_arg = pcall(ggml.init)
assert(not ok_missing_arg, "ggml.init() without args should fail")
assert(type(err_missing_arg) == "string", "Expected an error string from invalid call")

ggml.free(ctx)

print("PASS: loaded ggml and validated matmul output")
